In [1]:
import pandas as pd
import numpy as np
import json
import itertools
from itertools import islice
from matplotlib import pyplot as plt
mydir = '/home/garrett/work/mixed_loop'

In [65]:
bad_6trim_array=[]
bad_6trim_df = pd.DataFrame(columns = ['word', 'tgt', 'pred'])
with open('/home/garrett/work/mixed_loop/checkpoint_6loop_compare_eval6/htcondor/dumped/debug/1333280/eval.valid.boots.199') as f:
    while True:
        next_n_lines = list(islice(f, 5))
        if not next_n_lines:
            break
        if next_n_lines[3][0]=='1': continue
        print(next_n_lines)
        word=next_n_lines[1][4:16]
        tgt=next_n_lines[2][4:-1]
        pred=next_n_lines[3][2:-1]
        data=[word, tgt, pred]
        bad_6trim_array.append(data)
bad_6trim_df = pd.DataFrame(bad_6trim_array, columns = ['word', 'tgt', 'pred'])

['Equation 3 (0/1)\n', 'src=caabddbdbdce\n', 'tgt=-768\n', '0 768\n', '\n']
['Equation 18 (0/1)\n', 'src=aeafabfaeaee\n', 'tgt=256\n', '0 -256\n', '\n']
['Equation 25 (0/1)\n', 'src=ccaceeccdbdd\n', 'tgt=480\n', '0 -480\n', '\n']
['Equation 40 (0/1)\n', 'src=bbbaaafaeaee\n', 'tgt=768\n', '0 1760\n', '\n']
['Equation 44 (0/1)\n', 'src=ccddbbccbddd\n', 'tgt=48\n', '0 -48\n', '\n']
['Equation 58 (0/1)\n', 'src=ccaeccdbbbdd\n', 'tgt=128\n', '0 -448\n', '\n']
['Equation 59 (0/1)\n', 'src=bbbbbcafacee\n', 'tgt=720\n', '0 -720\n', '\n']
['Equation 62 (0/1)\n', 'src=bddbcaaeafae\n', 'tgt=112\n', '0 -112\n', '\n']
['Equation 69 (0/1)\n', 'src=cbbcdbceeece\n', 'tgt=2080\n', '0 -2080\n', '\n']
['Equation 76 (0/1)\n', 'src=aabceaaabdce\n', 'tgt=-48\n', '0 48\n', '\n']
['Equation 78 (0/1)\n', 'src=aaaecbfbabdd\n', 'tgt=-1904\n', '0 1904\n', '\n']
['Equation 86 (0/1)\n', 'src=bdbaaccececd\n', 'tgt=1920\n', '0 -1920\n', '\n']
['Equation 89 (0/1)\n', 'src=aaaaabaeafae\n', 'tgt=1104\n', '0 1008\n', '\n']
['Equation 107 (0/1)\n', 'src=bbcafacecbdd\n', 'tgt=-512\n', '0 512\n', '\n']
['Equation 110 (0/1)\n', 'src=ccbabcdcccdd\n', 'tgt=-2592\n', '0 1312\n', '\n']
['Equation 145 (0/1)\n', 'src=aabcaccabfbd\n', 'tgt=232\n', '0 -232\n', '\n']
['Equation 148 (0/1)\n', 'src=ccbffbdddddd\n', 'tgt=14080\n', '0 -3072\n', '\n']
['Equation 152 (0/1)\n', 'src=bbcccaeaffae\n', 'tgt=-9568\n', '0 9568\n', '\n']
['Equation 183 (0/1)\n', 'src=aaacaafbcdcd\n', 'tgt=336\n', '0 -336\n', '\n']
['Equation 190 (0/1)\n', 'src=aeaeacdcecdd\n', 'tgt=896\n', '0 128\n', '\n']
['Equation 193 (0/1)\n', 'src=bfbfabacecdd\n', 'tgt=-944\n', '0 1248\n', '\n']
['Equation 194 (0/1)\n', 'src=ccabaffbbbbd\n', 'tgt=0\n', '0 -3392\n', '\n']
['Equation 200 (0/1)\n', 'src=babbabddbaee\n', 'tgt=-704\n', '0 704\n', '\n']
['Equation 201 (0/1)\n', 'src=ccbdbbcbceee\n', 'tgt=1296\n', '0 1104\n', '\n']
['Equation 215 (0/1)\n', 'src=bbbabffbcece\n', 'tgt=288\n', '0 -288\n', '\n']
['Equation 218 (0/1)\n', 'src=aeecbcbcaece\n', 'tgt=-768\n', '0 768\n', '\n']
['Equation 229 (0/1)\n', 'src=bfffbbbddbdd\n', 'tgt=9472\n', '0 3776\n', '\n']
['Equation 239 (0/1)\n', 'src=afffbbffbddd\n', 'tgt=-21248\n', '0 1408\n', '\n']
['Equation 240 (0/1)\n', 'src=cecaeeafbbbd\n', 'tgt=-5504\n', '0 5504\n', '\n']
['Equation 250 (0/1)\n', 'src=bbaabfabbdce\n', 'tgt=-192\n', '0 192\n', '\n']
['Equation 259 (0/1)\n', 'src=ceaaccbfafff\n', 'tgt=176\n', '0 80\n', '\n']
['Equation 267 (0/1)\n', 'src=aaaaceaaeecd\n', 'tgt=-1120\n', '0 1568\n', '\n']
['Equation 273 (0/1)\n', 'src=ccdbfabdbddd\n', 'tgt=64\n', '0 -64\n', '\n']
['Equation 281 (0/1)\n', 'src=bbaceeaccbdd\n', 'tgt=-160\n', '0 160\n', '\n']
['Equation 288 (0/1)\n', 'src=aaffbfbabbdd\n', 'tgt=-864\n', '0 864\n', '\n']
['Equation 291 (0/1)\n', 'src=abaabbdcceee\n', 'tgt=832\n', '0 544\n', '\n']
['Equation 297 (0/1)\n', 'src=ccdbbacacdce\n', 'tgt=-280\n', '0 280\n', '\n']
['Equation 309 (0/1)\n', 'src=ccbaffbddbdd\n', 'tgt=2560\n', '0 -2560\n', '\n']
['Equation 311 (0/1)\n', 'src=aaecddbcdddd\n', 'tgt=1280\n', '0 1408\n', '\n']
['Equation 316 (0/1)\n', 'src=bcaeccaceeae\n', 'tgt=-480\n', '0 480\n', '\n']
['Equation 321 (0/1)\n', 'src=bbbabdccdccd\n', 'tgt=928\n', '0 416\n', '\n']
['Equation 322 (0/1)\n', 'src=ccbcaaeeeccd\n', 'tgt=3296\n', '0 -2560\n', '\n']
['Equation 335 (0/1)\n', 'src=ccbffaececdd\n', 'tgt=1152\n', '0 -1152\n', '\n']
['Equation 343 (0/1)\n', 'src=bbddcecabfbd\n', 'tgt=320\n', '0 -320\n', '\n']
['Equation 347 (0/1)\n', 'src=ccaabbfbbbdd\n', 'tgt=-1360\n', '0 1328\n', '\n']
['Equation 350 (0/1)\n', 'src=afafabaeafbd\n', 'tgt=784\n', '0 -784\n', '\n']
['Equation 358 (0/1)\n', 'src=aacdbaabaece\n', 'tgt=-128\n', '0 128\n', '\n']
['Equation 362 (0/1)\n', 'src=aacdcbaacecd\n', 'tgt=-128\n', '0 128\n', '\n']
['Equation 368 (0/1)\n', 'src=ccbdcaeeccce\n', 'tgt=-576\n', '0 1216\n', '\n']
['Equation 372 (0/1)\n', 'src=bbbaeeacdcdd\n', 'tgt=-704\n', '0 704\n', '\n']
['Equation 373 (0/1)\n', 'src=cabccecdccce\n', 'tgt=-1664\n', '0 1664\n', '\n']
['Equation 377 (0/1)\n', 'src=baaeacbdcece\n', 'tgt=-384\n', '0 384\n', '\n']
['Equation 382 (0/1)\n', 'src=bbdbaecabfbd\n', 'tgt=160\n', '0 -160\n', '\n']
['Equation 384 (0/1)\n', 'src=bbcdbfabcece\n', 'tgt=-160\n', '0 160\n', '\n']
['Equation 387 (0/1)\n', 'src=cbceecacbcee\n', 'tgt=384\n', '0 -384\n', '\n']
['Equation 397 (0/1)\n', 'src=bcaabbaaeecd\n', 'tgt=1152\n', '0 -1152\n', '\n']
['Equation 406 (0/1)\n', 'src=bbbfaabaccee\n', 'tgt=1416\n', '0 -1416\n', '\n']
['Equation 412 (0/1)\n', 'src=bbaaeafbcdbd\n', 'tgt=288\n', '0 -288\n', '\n']
['Equation 413 (0/1)\n', 'src=afbceccdcccd\n', 'tgt=-6656\n', '0 6656\n', '\n']
['Equation 414 (0/1)\n', 'src=ccababfbfbdd\n', 'tgt=1760\n', '0 -1824\n', '\n']
['Equation 417 (0/1)\n', 'src=bbddbdbcbbdd\n', 'tgt=-544\n', '0 544\n', '\n']
['Equation 419 (0/1)\n', 'src=aabaceabcdce\n', 'tgt=-608\n', '0 560\n', '\n']
['Equation 422 (0/1)\n', 'src=abacecdddddd\n', 'tgt=-49920\n', '0 25728\n', '\n']
['Equation 424 (0/1)\n', 'src=ccabbcdbbbdd\n', 'tgt=-288\n', '0 288\n', '\n']
['Equation 430 (0/1)\n', 'src=aababbdceeae\n', 'tgt=-1312\n', '0 1312\n', '\n']
['Equation 433 (0/1)\n', 'src=cccdbbaffbdd\n', 'tgt=-6368\n', '0 4128\n', '\n']
['Equation 441 (0/1)\n', 'src=aceaacccdbdd\n', 'tgt=-512\n', '0 512\n', '\n']
['Equation 444 (0/1)\n', 'src=affabbcbbaee\n', 'tgt=264\n', '0 -264\n', '\n']
['Equation 447 (0/1)\n', 'src=aabccecbbddd\n', 'tgt=832\n', '0 -832\n', '\n']
['Equation 448 (0/1)\n', 'src=bbbaeaacafbd\n', 'tgt=-576\n', '0 576\n', '\n']
['Equation 449 (0/1)\n', 'src=bbcaffbbfbbd\n', 'tgt=-2752\n', '0 1216\n', '\n']
['Equation 460 (0/1)\n', 'src=accecabbddce\n', 'tgt=384\n', '0 -384\n', '\n']
['Equation 467 (0/1)\n', 'src=bcceeeeeeccd\n', 'tgt=-12800\n', '0 -5376\n', '\n']
['Equation 474 (0/1)\n', 'src=cccaceeecddd\n', 'tgt=-3136\n', '0 832\n', '\n']
['Equation 489 (0/1)\n', 'src=cbaccaeaacdd\n', 'tgt=-128\n', '0 128\n', '\n']
['Equation 490 (0/1)\n', 'src=ccddbcbcbbdd\n', 'tgt=552\n', '0 392\n', '\n']
['Equation 495 (0/1)\n', 'src=ccdcaccbffae\n', 'tgt=-560\n', '0 -624\n', '\n']
['Equation 511 (0/1)\n', 'src=bfaaaeaaeece\n', 'tgt=-320\n', '0 320\n', '\n']
['Equation 514 (0/1)\n', 'src=bdccccafbbdd\n', 'tgt=800\n', '0 -1008\n', '\n']
['Equation 521 (0/1)\n', 'src=bbbaabcbffae\n', 'tgt=528\n', '0 336\n', '\n']
['Equation 534 (0/1)\n', 'src=bbcababfbfae\n', 'tgt=176\n', '0 -176\n', '\n']
['Equation 538 (0/1)\n', 'src=ccccaccbccdd\n', 'tgt=-240\n', '0 240\n', '\n']
['Equation 548 (0/1)\n', 'src=caeccecdceaf\n', 'tgt=-896\n', '0 896\n', '\n']
['Equation 552 (0/1)\n', 'src=bbcbabbbddce\n', 'tgt=-1200\n', '0 1200\n', '\n']
['Equation 554 (0/1)\n', 'src=ccdcdcbdbbdd\n', 'tgt=-2880\n', '0 -3760\n', '\n']
['Equation 572 (0/1)\n', 'src=baaabcbceeae\n', 'tgt=1312\n', '0 -1312\n', '\n']
['Equation 575 (0/1)\n', 'src=bdcbdcccafae\n', 'tgt=-40\n', '0 40\n', '\n']
['Equation 614 (0/1)\n', 'src=aaceecdcaeae\n', 'tgt=672\n', '0 -672\n', '\n']
['Equation 620 (0/1)\n', 'src=ccaffacdcecd\n', 'tgt=-512\n', '0 512\n', '\n']
['Equation 625 (0/1)\n', 'src=aacddcabcece\n', 'tgt=160\n', '0 -160\n', '\n']
['Equation 626 (0/1)\n', 'src=ceacecbdbbdd\n', 'tgt=-32\n', '0 32\n', '\n']
['Equation 630 (0/1)\n', 'src=ceacccceafae\n', 'tgt=1296\n', '0 1088\n', '\n']
['Equation 646 (0/1)\n', 'src=ceafbffbdddd\n', 'tgt=25344\n', '0 1024\n', '\n']
['Equation 647 (0/1)\n', 'src=aeaaabfbabdd\n', 'tgt=-256\n', '0 256\n', '\n']
['Equation 654 (0/1)\n', 'src=ccbcdcbbcddd\n', 'tgt=-1376\n', '0 1376\n', '\n']
['Equation 661 (0/1)\n', 'src=aabddcccdccd\n', 'tgt=384\n', '0 -384\n', '\n']
['Equation 679 (0/1)\n', 'src=ccddbccbabdd\n', 'tgt=56\n', '0 -56\n', '\n']
['Equation 682 (0/1)\n', 'src=cacaabbcddce\n', 'tgt=-544\n', '0 -1696\n', '\n']
['Equation 689 (0/1)\n', 'src=bbdceaccabdd\n', 'tgt=-288\n', '0 288\n', '\n']
['Equation 696 (0/1)\n', 'src=bcdbbfbcdddd\n', 'tgt=2176\n', '0 0\n', '\n']
['Equation 700 (0/1)\n', 'src=bfbaeeafafae\n', 'tgt=1344\n', '0 -2504\n', '\n']
['Equation 703 (0/1)\n', 'src=cceabaaabdcd\n', 'tgt=200\n', '0 -200\n', '\n']
['Equation 717 (0/1)\n', 'src=ceeccabddddd\n', 'tgt=3968\n', '0 -3264\n', '\n']
['Equation 733 (0/1)\n', 'src=accbaecceece\n', 'tgt=1344\n', '0 -1312\n', '\n']
['Equation 744 (0/1)\n', 'src=ccdbcbcbbfae\n', 'tgt=3888\n', '0 -3888\n', '\n']
['Equation 753 (0/1)\n', 'src=aaabcabfbbdd\n', 'tgt=144\n', '0 -336\n', '\n']
['Equation 763 (0/1)\n', 'src=aeacbfaeeeae\n', 'tgt=3424\n', '0 -3424\n', '\n']
['Equation 765 (0/1)\n', 'src=ccceaacaeece\n', 'tgt=-2096\n', '0 8784\n', '\n']
['Equation 773 (0/1)\n', 'src=bccbdcdcdddd\n', 'tgt=6848\n', '0 6400\n', '\n']
['Equation 788 (0/1)\n', 'src=aabbacbccbdd\n', 'tgt=-56\n', '0 56\n', '\n']
['Equation 789 (0/1)\n', 'src=ccabcafbbbdd\n', 'tgt=-1072\n', '0 496\n', '\n']
['Equation 794 (0/1)\n', 'src=ccbbbfaaaaaf\n', 'tgt=24064\n', '0 -9984\n', '\n']
['Equation 797 (0/1)\n', 'src=aabcafaaecee\n', 'tgt=800\n', '0 -800\n', '\n']
['Equation 798 (0/1)\n', 'src=bcbaabceaecd\n', 'tgt=208\n', '0 -208\n', '\n']
['Equation 799 (0/1)\n', 'src=aabcccceeeae\n', 'tgt=5088\n', '0 -5088\n', '\n']
['Equation 804 (0/1)\n', 'src=cbcbfffbdddd\n', 'tgt=-18176\n', '0 18176\n', '\n']
['Equation 806 (0/1)\n', 'src=aabaeaeaeeae\n', 'tgt=-8256\n', '0 8256\n', '\n']
['Equation 825 (0/1)\n', 'src=bbaabafbbbdd\n', 'tgt=-15680\n', '0 15128\n', '\n']
['Equation 830 (0/1)\n', 'src=ccdbaeececce\n', 'tgt=-320\n', '0 320\n', '\n']
['Equation 858 (0/1)\n', 'src=bababbaeaeae\n', 'tgt=-960\n', '0 960\n', '\n']
['Equation 861 (0/1)\n', 'src=accdbdbcecdd\n', 'tgt=576\n', '0 -576\n', '\n']
['Equation 865 (0/1)\n', 'src=afaeeabfffbd\n', 'tgt=-1920\n', '0 1920\n', '\n']
['Equation 869 (0/1)\n', 'src=bcceaafbfbdd\n', 'tgt=320\n', '0 -320\n', '\n']
['Equation 874 (0/1)\n', 'src=bffbccbfaeae\n', 'tgt=-4256\n', '0 4256\n', '\n']
['Equation 878 (0/1)\n', 'src=aeaaafbfbcdd\n', 'tgt=-1216\n', '0 1216\n', '\n']
['Equation 893 (0/1)\n', 'src=aaaabaffaeae\n', 'tgt=-2688\n', '0 288\n', '\n']
['Equation 902 (0/1)\n', 'src=afbbddcccddd\n', 'tgt=3392\n', '0 -3392\n', '\n']
['Equation 908 (0/1)\n', 'src=cdbbaececece\n', 'tgt=3008\n', '0 -3008\n', '\n']
['Equation 913 (0/1)\n', 'src=babafbbaeeae\n', 'tgt=-1376\n', '0 1376\n', '\n']
['Equation 920 (0/1)\n', 'src=bcbfaaecceee\n', 'tgt=576\n', '0 -576\n', '\n']
['Equation 929 (0/1)\n', 'src=ccdcbabddcce\n', 'tgt=736\n', '0 -544\n', '\n']
['Equation 933 (0/1)\n', 'src=abbbafbabfae\n', 'tgt=336\n', '0 -336\n', '\n']
['Equation 935 (0/1)\n', 'src=ccceecdbdbff\n', 'tgt=-960\n', '0 960\n', '\n']
['Equation 958 (0/1)\n', 'src=bbfbfbaafaee\n', 'tgt=1632\n', '0 -1792\n', '\n']
['Equation 964 (0/1)\n', 'src=ceaecacaffae\n', 'tgt=-880\n', '0 880\n', '\n']
['Equation 978 (0/1)\n', 'src=aceaeacbcdbd\n', 'tgt=272\n', '0 -272\n', '\n']
['Equation 979 (0/1)\n', 'src=afbafacbdcce\n', 'tgt=768\n', '0 -768\n', '\n']
['Equation 981 (0/1)\n', 'src=affbbbdccddd\n', 'tgt=-2528\n', '0 -1120\n', '\n']
['Equation 982 (0/1)\n', 'src=abfaaaeaaeee\n', 'tgt=-2848\n', '0 -6144\n', '\n']
['Equation 987 (0/1)\n', 'src=bbdddcbdcece\n', 'tgt=-736\n', '0 736\n', '\n']
['Equation 988 (0/1)\n', 'src=caabaabcbdce\n', 'tgt=-120\n', '0 120\n', '\n']
['Equation 997 (0/1)\n', 'src=aeacbabfaeee\n', 'tgt=1280\n', '0 1248\n', '\n']
['Equation 1002 (0/1)\n', 'src=aaafbdbacbdd\n', 'tgt=1152\n', '0 -1152\n', '\n']
['Equation 1008 (0/1)\n', 'src=aeaaaaaecddd\n', 'tgt=-56032\n', '0 -16608\n', '\n']
['Equation 1015 (0/1)\n', 'src=bbfbcbbccbdd\n', 'tgt=-304\n', '0 304\n', '\n']
['Equation 1029 (0/1)\n', 'src=cbdcaacaaeee\n', 'tgt=224\n', '0 0\n', '\n']
['Equation 1032 (0/1)\n', 'src=bcbdbcafafae\n', 'tgt=288\n', '0 -288\n', '\n']
['Equation 1040 (0/1)\n', 'src=bbceabfabddd\n', 'tgt=-640\n', '0 640\n', '\n']
['Equation 1056 (0/1)\n', 'src=ccecabbaecce\n', 'tgt=-560\n', '0 560\n', '\n']
['Equation 1058 (0/1)\n', 'src=cbcaaeecceae\n', 'tgt=-576\n', '0 576\n', '\n']
['Equation 1070 (0/1)\n', 'src=aaeeabcccddd\n', 'tgt=720\n', '0 -624\n', '\n']
['Equation 1115 (0/1)\n', 'src=cccaaeaffaee\n', 'tgt=-2528\n', '0 2496\n', '\n']
['Equation 1131 (0/1)\n', 'src=baaafabcdbdd\n', 'tgt=992\n', '0 -992\n', '\n']
['Equation 1153 (0/1)\n', 'src=aaccdbdddcce\n', 'tgt=-64\n', '0 -1408\n', '\n']
['Equation 1166 (0/1)\n', 'src=acaeaffaafae\n', 'tgt=-704\n', '0 -640\n', '\n']
['Equation 1176 (0/1)\n', 'src=caabfffaaeae\n', 'tgt=-3392\n', '0 3008\n', '\n']
['Equation 1186 (0/1)\n', 'src=cccceeaffbdd\n', 'tgt=192\n', '0 -192\n', '\n']
['Equation 1187 (0/1)\n', 'src=aeaecabacddd\n', 'tgt=-1136\n', '0 1136\n', '\n']
['Equation 1192 (0/1)\n', 'src=aabbabdcccdd\n', 'tgt=-3056\n', '0 1968\n', '\n']
['Equation 1204 (0/1)\n', 'src=bbbbafbaceae\n', 'tgt=-96\n', '0 96\n', '\n']
['Equation 1219 (0/1)\n', 'src=bccccbbaeeee\n', 'tgt=-27312\n', '0 26544\n', '\n']
['Equation 1224 (0/1)\n', 'src=bddbfbdbbddd\n', 'tgt=896\n', '0 5376\n', '\n']
['Equation 1225 (0/1)\n', 'src=ceaeaaaeabdd\n', 'tgt=1008\n', '0 -1008\n', '\n']
['Equation 1231 (0/1)\n', 'src=cccbaabfbfae\n', 'tgt=-576\n', '0 576\n', '\n']
['Equation 1237 (0/1)\n', 'src=acbaaabddcdd\n', 'tgt=-2960\n', '0 2960\n', '\n']
['Equation 1257 (0/1)\n', 'src=ceaecacbceae\n', 'tgt=520\n', '0 -520\n', '\n']
['Equation 1270 (0/1)\n', 'src=bcddbcceccdd\n', 'tgt=144\n', '0 -144\n', '\n']
['Equation 1276 (0/1)\n', 'src=ccdccbbbbdbd\n', 'tgt=3984\n', '0 -3984\n', '\n']
['Equation 1278 (0/1)\n', 'src=bbafbbcaccdd\n', 'tgt=-256\n', '0 256\n', '\n']
['Equation 1279 (0/1)\n', 'src=caacbbceafbd\n', 'tgt=80\n', '0 -80\n', '\n']
['Equation 1283 (0/1)\n', 'src=cccacecacece\n', 'tgt=-1104\n', '0 1104\n', '\n']
['Equation 1288 (0/1)\n', 'src=cccbabafbfaf\n', 'tgt=-720\n', '0 720\n', '\n']
['Equation 1299 (0/1)\n', 'src=aaecbccaceae\n', 'tgt=24\n', '0 -24\n', '\n']
['Equation 1300 (0/1)\n', 'src=aaaacaacdddd\n', 'tgt=-22080\n', '0 -20352\n', '\n']
['Equation 1301 (0/1)\n', 'src=ceabdccbdddd\n', 'tgt=-32\n', '0 32\n', '\n']
['Equation 1307 (0/1)\n', 'src=ceaacacccdbd\n', 'tgt=1000\n', '0 -1000\n', '\n']
['Equation 1326 (0/1)\n', 'src=accccabcccee\n', 'tgt=-1496\n', '0 1496\n', '\n']
['Equation 1327 (0/1)\n', 'src=bbafabfbdcee\n', 'tgt=-992\n', '0 512\n', '\n']
['Equation 1332 (0/1)\n', 'src=bbbacabcbbdd\n', 'tgt=-120\n', '0 120\n', '\n']
['Equation 1345 (0/1)\n', 'src=cbacaccdbdce\n', 'tgt=128\n', '0 -128\n', '\n']
['Equation 1347 (0/1)\n', 'src=cdcaaceeafae\n', 'tgt=-1120\n', '0 1120\n', '\n']
['Equation 1349 (0/1)\n', 'src=aafaccecbaee\n', 'tgt=80\n', '0 -80\n', '\n']
['Equation 1360 (0/1)\n', 'src=bbbbddcabaee\n', 'tgt=2480\n', '0 -2480\n', '\n']
['Equation 1365 (0/1)\n', 'src=aabceaeabcdd\n', 'tgt=608\n', '0 -608\n', '\n']
['Equation 1366 (0/1)\n', 'src=afaecafbcdce\n', 'tgt=-640\n', '0 640\n', '\n']
['Equation 1374 (0/1)\n', 'src=ccaaacbffbdd\n', 'tgt=-15744\n', '0 15744\n', '\n']
['Equation 1379 (0/1)\n', 'src=ceeecddcceee\n', 'tgt=-9984\n', '0 -5504\n', '\n']
['Equation 1381 (0/1)\n', 'src=aafbaeeeceee\n', 'tgt=4608\n', '0 3072\n', '\n']
['Equation 1389 (0/1)\n', 'src=ccdceeeeafae\n', 'tgt=0\n', '0 11008\n', '\n']
['Equation 1396 (0/1)\n', 'src=bbacecbcbcdd\n', 'tgt=240\n', '0 -240\n', '\n']
['Equation 1398 (0/1)\n', 'src=aaafffabaeae\n', 'tgt=-1152\n', '0 1152\n', '\n']
['Equation 1401 (0/1)\n', 'src=ceeabfafaeae\n', 'tgt=-960\n', '0 -736\n', '\n']
['Equation 1403 (0/1)\n', 'src=aafacbceabdd\n', 'tgt=80\n', '0 -80\n', '\n']
['Equation 1404 (0/1)\n', 'src=bbaacbdbaeee\n', 'tgt=1120\n', '0 -1120\n', '\n']
['Equation 1411 (0/1)\n', 'src=bfbddddbbddd\n', 'tgt=13568\n', '0 6656\n', '\n']
['Equation 1418 (0/1)\n', 'src=ccbceeeeccce\n', 'tgt=-9856\n', '0 9856\n', '\n']
['Equation 1420 (0/1)\n', 'src=bfbaaeaaeecd\n', 'tgt=64\n', '0 -64\n', '\n']
['Equation 1431 (0/1)\n', 'src=cccdcdcbfbdd\n', 'tgt=1856\n', '0 -1856\n', '\n']
['Equation 1433 (0/1)\n', 'src=acacaaaecddd\n', 'tgt=-6080\n', '0 4928\n', '\n']
['Equation 1441 (0/1)\n', 'src=ccaaacddcddd\n', 'tgt=-16832\n', '0 -10080\n', '\n']
['Equation 1450 (0/1)\n', 'src=aafbddbbabdd\n', 'tgt=320\n', '0 -320\n', '\n']
['Equation 1454 (0/1)\n', 'src=aaceabcabfbd\n', 'tgt=120\n', '0 -120\n', '\n']
['Equation 1456 (0/1)\n', 'src=ccafbddbdcce\n', 'tgt=512\n', '0 -512\n', '\n']
['Equation 1469 (0/1)\n', 'src=ccacaaacdbdd\n', 'tgt=11968\n', '0 -11968\n', '\n']
['Equation 1477 (0/1)\n', 'src=aaaabbbdbfaf\n', 'tgt=-528\n', '0 528\n', '\n']
['Equation 1496 (0/1)\n', 'src=caeeaacdccce\n', 'tgt=416\n', '0 1792\n', '\n']
['Equation 1502 (0/1)\n', 'src=bbafbcabaeee\n', 'tgt=240\n', '0 -240\n', '\n']
['Equation 1503 (0/1)\n', 'src=cccbcbcddcce\n', 'tgt=-8896\n', '0 10304\n', '\n']
['Equation 1508 (0/1)\n', 'src=afaeeacaafaf\n', 'tgt=-768\n', '0 768\n', '\n']
['Equation 1514 (0/1)\n', 'src=bdceaacecaee\n', 'tgt=-640\n', '0 640\n', '\n']
['Equation 1516 (0/1)\n', 'src=ceeeaacdccce\n', 'tgt=-4224\n', '0 -4608\n', '\n']
['Equation 1517 (0/1)\n', 'src=caaabbcecddd\n', 'tgt=-3056\n', '0 -3168\n', '\n']
['Equation 1522 (0/1)\n', 'src=ceeeaaeecdce\n', 'tgt=-9536\n', '0 -9216\n', '\n']
['Equation 1524 (0/1)\n', 'src=cacbfacdbcee\n', 'tgt=-512\n', '0 512\n', '\n']
['Equation 1528 (0/1)\n', 'src=bbbaacccaeee\n', 'tgt=-1408\n', '0 1408\n', '\n']
['Equation 1529 (0/1)\n', 'src=aeccabdceeae\n', 'tgt=256\n', '0 -256\n', '\n']
['Equation 1530 (0/1)\n', 'src=aacddbbbacdd\n', 'tgt=160\n', '0 -160\n', '\n']
['Equation 1536 (0/1)\n', 'src=aeeecddbbdbd\n', 'tgt=0\n', '0 -1792\n', '\n']
['Equation 1541 (0/1)\n', 'src=cdccabcceeae\n', 'tgt=240\n', '0 -240\n', '\n']
['Equation 1546 (0/1)\n', 'src=aaaacbbaffae\n', 'tgt=-1776\n', '0 1776\n', '\n']
['Equation 1552 (0/1)\n', 'src=affaececdbdd\n', 'tgt=-1408\n', '0 1408\n', '\n']
['Equation 1557 (0/1)\n', 'src=acbacbaeecce\n', 'tgt=448\n', '0 -448\n', '\n']
['Equation 1559 (0/1)\n', 'src=bcddcaeecbff\n', 'tgt=-160\n', '0 160\n', '\n']
['Equation 1561 (0/1)\n', 'src=bbcbfabdcccd\n', 'tgt=1856\n', '0 1984\n', '\n']
['Equation 1586 (0/1)\n', 'src=ceaababfaecd\n', 'tgt=-304\n', '0 304\n', '\n']
['Equation 1591 (0/1)\n', 'src=bbbbbcbacdce\n', 'tgt=96\n', '0 -96\n', '\n']
['Equation 1593 (0/1)\n', 'src=aaacbcbacbdd\n', 'tgt=824\n', '0 -824\n', '\n']
['Equation 1614 (0/1)\n', 'src=bddddcecacdd\n', 'tgt=-6016\n', '0 6016\n', '\n']
['Equation 1629 (0/1)\n', 'src=cbceceeecdcd\n', 'tgt=-7872\n', '0 -7104\n', '\n']
['Equation 1653 (0/1)\n', 'src=bdcacbaccece\n', 'tgt=512\n', '0 -512\n', '\n']
['Equation 1661 (0/1)\n', 'src=aabccdcceeae\n', 'tgt=160\n', '0 -608\n', '\n']
['Equation 1674 (0/1)\n', 'src=aabbbfacaaee\n', 'tgt=-656\n', '0 656\n', '\n']
['Equation 1680 (0/1)\n', 'src=bdbacecaccdd\n', 'tgt=-384\n', '0 384\n', '\n']
['Equation 1681 (0/1)\n', 'src=aeaaffaaeeee\n', 'tgt=-2368\n', '0 -3392\n', '\n']
['Equation 1691 (0/1)\n', 'src=bbdbaaaeafae\n', 'tgt=-336\n', '0 -112\n', '\n']
['Equation 1700 (0/1)\n', 'src=cceccaaaeeae\n', 'tgt=-3056\n', '0 3056\n', '\n']
['Equation 1708 (0/1)\n', 'src=aacaaeeecece\n', 'tgt=-5888\n', '0 5888\n', '\n']
['Equation 1711 (0/1)\n', 'src=aacceecddcee\n', 'tgt=-3520\n', '0 1856\n', '\n']
['Equation 1716 (0/1)\n', 'src=ceecaceaffae\n', 'tgt=1600\n', '0 1504\n', '\n']
['Equation 1719 (0/1)\n', 'src=aafaabbccaee\n', 'tgt=296\n', '0 -208\n', '\n']
['Equation 1721 (0/1)\n', 'src=ceaeeaecdddd\n', 'tgt=4288\n', '0 2560\n', '\n']
['Equation 1722 (0/1)\n', 'src=bacdddccdcdd\n', 'tgt=256\n', '0 -256\n', '\n']
['Equation 1727 (0/1)\n', 'src=ccecafbcbdce\n', 'tgt=240\n', '0 -240\n', '\n']
['Equation 1728 (0/1)\n', 'src=cdbaafaaaeae\n', 'tgt=2944\n', '0 1664\n', '\n']
['Equation 1733 (0/1)\n', 'src=aaffbbfaaaee\n', 'tgt=-1008\n', '0 1264\n', '\n']
['Equation 1748 (0/1)\n', 'src=aacbcaaeabdd\n', 'tgt=416\n', '0 -416\n', '\n']
['Equation 1761 (0/1)\n', 'src=acaeaccacece\n', 'tgt=-144\n', '0 144\n', '\n']
['Equation 1763 (0/1)\n', 'src=bfbbffaaaaaf\n', 'tgt=6016\n', '0 -6016\n', '\n']
['Equation 1792 (0/1)\n', 'src=caceeaecddce\n', 'tgt=-384\n', '0 384\n', '\n']
['Equation 1797 (0/1)\n', 'src=ccaaccabccee\n', 'tgt=176\n', '0 -176\n', '\n']
['Equation 1800 (0/1)\n', 'src=bbfafabbceee\n', 'tgt=-2480\n', '0 2192\n', '\n']
['Equation 1805 (0/1)\n', 'src=ccaaaccafbdd\n', 'tgt=-11328\n', '0 -11360\n', '\n']

In [66]:
bad_mix_array=[]
bad_mix_df = pd.DataFrame(columns = ['word', 'tgt', 'pred'])
with open('/home/garrett/work/mixed_loop/checkpoint_5loop6loopmix_eval6/htcondor/dumped/debug/1333300/eval.valid.boots.199') as f:
    while True:
        next_n_lines = list(islice(f, 5))
        if not next_n_lines:
            break
        if next_n_lines[3][0]=='1': continue
        word=next_n_lines[1][4:16]
        tgt=next_n_lines[2][4:-1]
        pred=next_n_lines[3][2:-1]
        data=[word, tgt, pred]
        bad_mix_array.append(data)
bad_mix_df = pd.DataFrame(bad_mix_array, columns = ['word', 'tgt', 'pred'])

In [67]:
bad_mix_df

             word     tgt    pred
0    babcbcdcabdd     416    -416
1    abbffbabfbdd     224    -224
2    bbbaaafaeaee     768   -1568
3    aaaecbfbabdd   -1904    1904
4    bfbfabacecdd    -944     944
5    ccbdbbcbceee    1296    1136
6    abbbcccbdddd     576    -576
7    bbbabffbcece     288    -288
8    abbfbbbfacdd   -3696    3696
9    acaccaabaeae     -24      24
10   bcdceeaeaeae   -1664   -3072
11   afbacbbfabdd     -80      80
12   bbbabdccdccd     928     512
13   aacdbaabaece    -128     128
14   aacdcbaacecd    -128     128
15   cbceecacbcee     384    -384
16   aafafacacbdd     112    -112
17   ccbdcbdbcece    -320     320
18   ccababfbfbdd    1760     192
19   bbbaeaacafbd    -576     576
20   bbcaffbbfbbd   -2752   -1216
21   bacaecdcdcce   -1664   -1472
22   bfaaeaccdddd    -640     640
23   aaaaaacdbbdd       0    1056
24   ccaffacdcecd    -512     512
25   cddbcaafaaaf   -5760    5760
26   cdbbffbbffae    -992   -1376
27   ccabcafbbbdd   -1072   -1440
28   baffaeabccee     160    -160
29   afbacaeabddd    -608     608
30   bbcbacdbacdd     176    -176
31   aeaaafbfbcdd   -1216    1216
32   babcacdceece    -672     672
33   aeacbabfaeee    1280   -1248
34   bcaafaabbdce     128    -128
35   aaeeabcccddd     720    -720
36   caaccbfbddce     192      96
37   baaafabcdbdd     992    -992
38   bbafbbcaccdd    -256     256
39   bbbacabcbbdd    -120     120
40   aeaacccacece     824    -824
41   bbaacbdbaeee    1120   -1120
42   cacbbfbcbbdd    -208     208
43   ceaaaccbcddd      80     -80
44   cecdbbbcabff     512    -512
45   aacddbbbacdd     160    -160
46   bdcbbbbbbbdd     480    -480
47   cbcdcaabacdd    -208     208
48   aaffabdcaeae    -160     160
49   afafbcabfbdd    -800     800
50   cbabfabbcbdd     256    -256
51   aabccdcceeae     160      32
52   bbdbaaaeafae    -336     336
53   acaeaccacece    -144     144
54   cbbbfffbdddd    5248   -5248
55   aacaeabaeeee    -256     256
56   bcbccabaeece    1040   -1040
57   bdbbbdcccdce   -3968    3968
58   babafabbabdd    -384     384
59   caecabffbbdd    -960     864
60   caeacaabdddd   -3040    3040
61   afbaabfacdcd     -48      48
62   bbdceceaabdd      64     -64
63   bcbccaaafbdd    -544     544
64   aabdbbbbfbdd   -1120    1120
65   cabcacdddcce    1312    1952
66   aafabfbcbcdd     176    -176
67   cdcbcccabcee    -128     128
68   ccbafbabccdd     416    -416
69   afaacaabdddd    -176    -768
70   bccccdcacbdd    -864     864
71   cbcecccbcddd     512    -512
72   bafaecacabdd    -288     288
73   bbceabcabfbd    -256     256
74   bbcccddcdcdd   -4448    4448
75   aeaecbccdddd    -704    -448
76   baacacccaeee     352    -352
77   ccbacecdcccd    3072   -3072
78   aacbffaaafae   -2144    2144
79   aecaabacdcce    -688     688
80   ccabbfbbbbdd     672    -672
81   bbfacaabccdd     120    -120
82   bbddbbccbddd     368     256
83   bbbaceaeccee    -416      32
84   aaafaaaacdce   10776  -10776
85   bcbbaecdbdce   -1152   -1024
86   ccecceecdbdd    2240    1088
87   aaacbceabbdd     576    -576
88   cbaacaccdddd    1920       0
89   aecbbbaccbdd     512    -512
90   bdcabbcdceae    -384     384
91   bbaceceaeaaf    -640     640
92   cceceaeeecce    -256    -640
93   babbdccbcdce     624    -624
94   bccacbbbffbd    -672    -752
95   baafabceecee    1120   -1120
96   ccbccccacbdd   -1200    1200
97   bafffabacaee     128    -128
98   ccbacaabdddd   -3024    3024
99   cbacceaaeeae    1312   -1312
100  bcacaceacecd    -128     128
101  babaccacbaee     -56      56
102  ccdbbaaaccdd     192    -192
103  accaecabdddd    3008   -3008
104  afaafbabbaee    1496   -1496
105  bbaabbbcbbdd     768    -768
106  acabaecaeeae     256    -256
107  afbbbfacddce    6208   -6208
108  bbbfabcbabdd   -1960    1960
109  bbabbccdbddd    2032   -1792
110  abbcdbbacbdd    -416     416
111  bbbcddcacbdd    -848     848
112  acaabaacdddd   10560  -10560
113  cdddcdccecce  -15360  -15056
114  ceecdcaaacdd    1344   -1344
115  aafaeceeecce   -4608   -4864
116  aceccbfbdbdd    -320     320
117  ccaaaecbffae   -1088    -800
118  bccbbcdbacdd    -832     832
119  cdcaaffacddd    1024   -1024
120  cceeecccdddd  -48192   48192
121  abceafbffbdd    -704     704
122  ccacbcacafbd      -8       8
123  bdbdcecbceae     384    -384
124  cccafbfabbdd     128    -128
125  baabbdbcbfbd    -560     560
126  afbfabacabdd    -520     520
127  baceaabacbdd     256    -256
128  cbbcbbcabfbd    -904     904
129  aabcaceaffae     640    -640
130  bbaabcddcece   10592  -10592
131  bdddcdddccce   45824   45888
132  ceabbdbbceee   -1536    1536
133  ccecdcbbbbdd     576    -576
134  caaeacbddddd    3392   -3392
135  bddbdcecdddd  -16256  -17408
136  bccacbcacbdd    -712     712
137  aababccabfbd     416    -416
138  bcdbdbafaeae     464    -464
139  cceabbacabdd     120    -120
140  aacabcaffaee   -1600    1600
141  accaffaecddd   -2112   -2560
142  bdddccacbbff    1152   -1152
143  aaaaecaacecd   30480  -30480
144  caaabababdbd     832    -832
145  ccdccbacdddd    -704     704
146  bbfbfbcaeeae      32     -32
147  ccbfbbbdcdce    1600   12272
148  ceecdcabcece    -128     128
149  aabbddbbcbdd     544    -544
150  baaacbcccece     120    -120
151  aaceaeaececd     384     448
152  aacecdbffbdd    2944    2880
153  bfafabbfafae     144    -144
154  cceabcceafbd    -240     240
155  bddceaeabaee   -1408    1408
156  ccbceaccddce     736    -736
157  affafbcacbdd   -1472    1472
158  aecbaafaaeae     192    -192
159  bbbafaaaeeee    2016   -2016
160  ccbbabbdbfae    -640     640
161  cbcbaabdbfae      80     -80
162  bdbdcccaffae      32     -32
163  aaccbcecabdd     560    -560
164  babbbddddddd   86400  -86400
165  ababceacabdd     560    -560
166  bbdccaeaaaee    -912     912
167  baceccbbdbdd      32     -32
168  ccabbbceafae    1152   -1152
169  bbbfaacacddd   -1456   -2256
170  aaccabbabcdd     312    -312
171  acbaaacdbcee     384    -384
172  ccbffaeabcee     192    -192
173  accaeacecbdd    -704     704
174  aaaabbfacaee     192    -192
175  aaecbffbfbdd   -2816    2816
176  ccccbddcbbdd     896     320
177  aacbfbcaeeae     992    -992
178  cbcbdcacdcce   -1024    1024
179  bcbfbccbdddd     416    -416
180  ceeaacbaffbd     512    -512
181  baabfbacbcee    -608     608
182  bbbdbacaeeee    5728   -5728
183  aaeeabbfbbdd      96     -96
184  ababfbcceccd     416     160
185  bdcccccafaee     208     464
186  cdbfafaeaece     512     256
187  afabafafabdd    -832     832
188  ceeeeaeeaaae   45056   45888
189  bfafabaabdce    -632     632
190  aecaceaabdce    -256     256
191  ccaeabdccddd    1120     992
192  bbbdbbcbcdcd   11064  -11064
193  bcdcaceeeccd     448     960
194  bbfbbcbdcaee    -432     432
195  bafbacbbccdd     136    -136
196  aabcabbddcee    -464     -16
197  baffabbaffbd    -208     -80
198  cddbfabfffae   -3392   -3264
199  aaacbcaffbdd   -2000    2000
200  aafbceaaeecd      32     -32
201  ceecbabbcdcd   -2800    2800
202  aeacdcbbdccd     768    -768
203  bcbddcbaffae     400    -400
204  aabdbbaeaaee     576    -576
205  aaeeecaaffae    -544       0
206  bffbdbfaecdd   -1792   -1536
207  cceeaeaccecd     864    -864
208  abbfbdcecddd     832      64
209  cecaeaabbddd     512     256
210  bdddcccaeeae   -2592   -4384
211  bbabccabcdbd    -392     392
212  cecbfabbaecd    -384     384
213  babafabfffae    1248     896
214  acaccdcdbbdd   -1120    1120
215  bcaabccaabdd     -64      64
216  cbbcaecaffae     -32      32
217  bbdccbbceeae    6368   -6368
218  ccdbcddbcdce     784    -784
219  aabfbfafbdce    -288     288
220  cccbababbbdd    -904     904
221  bcaceaeaaeae   -1344   -1216
222  bacaaaececce    1920    1280
223  bdbbbcceabdd      48     -48
224  abaabbbcbbdd   -1280    1280
225  abcdbcceccce     512    2048
226  bccacabdddcd     720    -720
227  abbbbbfaabdd     240    -240
228  ccaeeaceccce   -2400    -864
229  aaaffabbabdd     616    -616
230  bbdccacbaaee    -280     280
231  accaaecbbdce     -80      80
232  bccafbbcaaee     416    -416
233  ccdbcbabfbff    -784    -592
234  aaafafaeafae   24096  -24096
235  cddbbddddbbd   31488   23808
236  ccbceeaaaeae     608    1952
237  baaacbcbfbdd    -480     480
238  bcbbcbaceeae     608     960
239  ccdcabbacbdd     120    -120
240  cccbababafaf     904    1016
241  cddbacecbdbd     704    -704
242  cbbbbaaffbdd   -1456    1456
243  cdcdcceafaee   -1472    1376
244  bffaccdbcdce     704    -704
245  bbbbbfaaeaee  -29984   29984
246  bbbbbffbafbd     384    -384
247  bbdceacbdbdd    -576     576
248  cccddcbcdbdd       0   -3040
249  abafbcaffbdd    -672     672
250  cacabbbaecce    -112     112
251  bbceaeccdddd   -1088   -1280
252  acbbaaaabcee    -688     688
253  ccaecbfaeeae    -576     576
254  babbcbcaecee    1392   -1392
255  cdbaeaabacdd    -384     384
256  bddbcabcdcee   -1040   -1008
257  abaeabaabdbd     256    -256
258  aabbcccccece     256    -256
259  bacaafaafbbf     512       0
260  bbcaffbbbfae    -160     160
261  bbfbaabffbdd    1024    2304
262  ccbccacecece     528     176
263  cbaaeccbceee    -512    -256
264  cacaeaacdcce   -1216    1216
265  caafaaacabdd    -256     256
266  bcddcceaaaaf    -768     768
267  acceeccabddd    -496     496
268  ceaaceabccee    -128     128
269  aabcbcaaacdd    -200     200
270  babddbacabdd    -608     608
271  cccaeaaeaecd   -1728   -1152
272  cdbafaaaaece    -768     768
273  bbcdbbabacdd     208    -208
274  aabdbaeeeaff    1152   -1152
275  bdcafaaacddd    1536    2560

In [68]:
bad_6trim_df

              word    tgt   pred
0     caabddbdbdce   -768    768
1     aeafabfaeaee    256   -256
2     ccaceeccdbdd    480   -480
3     bbbaaafaeaee    768   1760
4     ccddbbccbddd     48    -48
...            ...    ...    ...
1367  bbccbfbceece   -896    896
1368  aaaaecdbbbdd  10272  -3072
1369  aaabfbbcddcd    736   -736
1370  aeecceabaece    768   -768
1371  aaecbbaceeae   -128    128

[1372 rows x 3 columns]

In [69]:
joint_df = pd.merge(bad_mix_df, bad_6trim_df, how ='inner', on =['word']).drop(columns=['tgt_y'])
joint_df = joint_df.rename(columns={'tgt_x': 'tgt', 'pred_x': 'pred_mix','pred_y': 'pred_6'})
pd.set_option('display.max_rows', 500)
print(joint_df)

             word     tgt pred_mix  pred_6
0    bbbaaafaeaee     768    -1568    1760
1    aaaecbfbabdd   -1904     1904    1904
2    bfbfabacecdd    -944      944    1248
3    ccbdbbcbceee    1296     1136    1104
4    bbbabffbcece     288     -288    -288
5    bbbabdccdccd     928      512     416
6    aacdbaabaece    -128      128     128
7    aacdcbaacecd    -128      128     128
8    cbceecacbcee     384     -384    -384
9    ccababfbfbdd    1760      192   -1824
10   bbbaeaacafbd    -576      576     576
11   bbcaffbbfbbd   -2752    -1216    1216
12   ccaffacdcecd    -512      512     512
13   ccabcafbbbdd   -1072    -1440     496
14   aeaaafbfbcdd   -1216     1216    1216
15   aeacbabfaeee    1280    -1248    1248
16   aaeeabcccddd     720     -720    -624
17   baaafabcdbdd     992     -992    -992
18   bbafbbcaccdd    -256      256     256
19   bbbacabcbbdd    -120      120     120
20   bbaacbdbaeee    1120    -1120   -1120
21   aacddbbbacdd     160     -160    -160
22   aabccdcceeae     160       32    -608
23   bbdbaaaeafae    -336      336    -112
24   acaeaccacece    -144      144     144
25   cbbbfffbdddd    5248    -5248  -11520
26   aacaeabaeeee    -256      256     256
27   bcbccabaeece    1040    -1040   -1232
28   caeacaabdddd   -3040     3040    1280
29   bbdceceaabdd      64      -64     -64
30   aafabfbcbcdd     176     -176    -176
31   ccbafbabccdd     416     -416    -416
32   bccccdcacbdd    -864      864     864
33   bbceabcabfbd    -256      256     256
34   ccbacecdcccd    3072    -3072     -64
35   aacbffaaafae   -2144     2144     608
36   ccabbfbbbbdd     672     -672    -672
37   bbfacaabccdd     120     -120    -120
38   bbbaceaeccee    -416       32     864
39   aaafaaaacdce   10776   -10776  -10776
40   bcbbaecdbdce   -1152    -1024    1152
41   ccecceecdbdd    2240     1088    1600
42   aaacbceabbdd     576     -576    -576
43   bdcabbcdceae    -384      384     384
44   bbaceceaeaaf    -640      640     640
45   cceceaeeecce    -256     -640   -1408
46   bccacbbbffbd    -672     -752    -624
47   ccbccccacbdd   -1200     1200    1200
48   ccbacaabdddd   -3024     3024    3024
49   ccdbbaaaccdd     192     -192    -192
50   accaecabdddd    3008    -3008   -3008
51   afaafbabbaee    1496    -1496   -1496
52   bbabbccdbddd    2032    -1792   -1768
53   acaabaacdddd   10560   -10560   -6192
54   ceecdcaaacdd    1344    -1344   -1344
55   aafaeceeecce   -4608    -4864   -3456
56   ccaaaecbffae   -1088     -800    1088
57   cceeecccdddd  -48192    48192   47712
58   cbbcbbcabfbd    -904      904     904
59   aabcaceaffae     640     -640   -1216
60   bbaabcddcece   10592   -10592  -10592
61   ceabbdbbceee   -1536     1536    1536
62   ccecdcbbbbdd     576     -576    -576
63   caaeacbddddd    3392    -3392   -6912
64   bcdbdbafaeae     464     -464    -464
65   aacabcaffaee   -1600     1600    1600
66   accaffaecddd   -2112    -2560      64
67   bdddccacbbff    1152    -1152   -1152
68   aaaaecaacecd   30480   -30480  -30480
69   ccdccbacdddd    -704      704     704
70   ccbfbbbdcdce    1600    12272   -1600
71   ceecdcabcece    -128      128     128
72   aaceaeaececd     384      448     640
73   aacecdbffbdd    2944     2880   16064
74   cceabcceafbd    -240      240     240
75   ccbceaccddce     736     -736    -736
76   bbbafaaaeeee    2016    -2016    5856
77   ccbbabbdbfae    -640      640     640
78   cbcbaabdbfae      80      -80     -80
79   aaccbcecabdd     560     -560    -560
80   babbbddddddd   86400   -86400  -45824
81   ababceacabdd     560     -560    -560
82   bbdccaeaaaee    -912      912   -1200
83   ccabbbceafae    1152    -1152   -1152
84   bbbfaacacddd   -1456    -2256   -3520
85   acbaaacdbcee     384     -384    -384
86   ccbffaeabcee     192     -192    -192
87   aaaabbfacaee     192     -192    -192
88   ccccbddcbbdd     896      320    -800
89   aacbfbcaeeae     992     -992    -992
90   bcbfbccbdddd     416     -416    -416
91   baabfbacbcee    -608      608     608
92   bbbdbacaeeee    5728    -5728   -3680
93   aaeeabbfbbdd      96      -96    -224
94   ccaeabdccddd    1120      992     992
95   bbbdbbcbcdcd   11064   -11064  -11544
96   bbfbbcbdcaee    -432      432     432
97   aaacbcaffbdd   -2000     2000    2000
98   aafbceaaeecd      32      -32     352
99   ceecbabbcdcd   -2800     2800    2800
100  aabdbbaeaaee     576     -576    -576
101  abbfbdcecddd     832       64    -832
102  cecaeaabbddd     512      256    -512
103  bdddcccaeeae   -2592    -4384     992
104  bbabccabcdbd    -392      392     392
105  acaccdcdbbdd   -1120     1120    1024
106  bbdccbbceeae    6368    -6368   -6368
107  aabfbfafbdce    -288      288     -96
108  cccbababbbdd    -904      904     904
109  bcaceaeaaeae   -1344    -1216    1344
110  bacaaaececce    1920     1280    1664
111  bccacabdddcd     720     -720    -592
112  aaaffabbabdd     616     -616    -616
113  bbdccacbaaee    -280      280     280
114  ccdbcbabfbff    -784     -592     784
115  ccbceeaaaeae     608     1952    -608
116  cdcdcceafaee   -1472     1376    1472
117  bbbbbfaaeaee  -29984    29984   30688
118  bbbbbffbafbd     384     -384    -384
119  bbdceacbdbdd    -576      576     576
120  abafbcaffbdd    -672      672     672
121  bbceaeccdddd   -1088    -1280   -1472
122  cdbaeaabacdd    -384      384     384
123  bbcaffbbbfae    -160      160     160
124  bbfbaabffbdd    1024     2304   -1024
125  ccbccacecece     528      176     272
126  caafaaacabdd    -256      256     256
127  aabcbcaaacdd    -200      200     200
128  babddbacabdd    -608      608     608
129  bbcdbbabacdd     208     -208    -208
130  aabdbaeeeaff    1152    -1152   -1152

In [70]:
left_df = pd.merge(bad_mix_df, bad_6trim_df, how ='left', on =['word'], indicator=True)
left_df = left_df[left_df["_merge"]=="left_only"].drop(columns=['tgt_y','pred_y','_merge'])
left_df = left_df.rename(columns={'tgt_x': 'tgt', 'pred_x': 'pred_mix'})
pd.set_option('display.max_rows', 500)
print(left_df)

             word     tgt pred_mix
0    babcbcdcabdd     416     -416
1    abbffbabfbdd     224     -224
6    abbbcccbdddd     576     -576
8    abbfbbbfacdd   -3696     3696
9    acaccaabaeae     -24       24
10   bcdceeaeaeae   -1664    -3072
11   afbacbbfabdd     -80       80
16   aafafacacbdd     112     -112
17   ccbdcbdbcece    -320      320
21   bacaecdcdcce   -1664    -1472
22   bfaaeaccdddd    -640      640
23   aaaaaacdbbdd       0     1056
25   cddbcaafaaaf   -5760     5760
26   cdbbffbbffae    -992    -1376
28   baffaeabccee     160     -160
29   afbacaeabddd    -608      608
30   bbcbacdbacdd     176     -176
32   babcacdceece    -672      672
34   bcaafaabbdce     128     -128
36   caaccbfbddce     192       96
40   aeaacccacece     824     -824
42   cacbbfbcbbdd    -208      208
43   ceaaaccbcddd      80      -80
44   cecdbbbcabff     512     -512
46   bdcbbbbbbbdd     480     -480
47   cbcdcaabacdd    -208      208
48   aaffabdcaeae    -160      160
49   afafbcabfbdd    -800      800
50   cbabfabbcbdd     256     -256
57   bdbbbdcccdce   -3968     3968
58   babafabbabdd    -384      384
59   caecabffbbdd    -960      864
61   afbaabfacdcd     -48       48
63   bcbccaaafbdd    -544      544
64   aabdbbbbfbdd   -1120     1120
65   cabcacdddcce    1312     1952
67   cdcbcccabcee    -128      128
69   afaacaabdddd    -176     -768
71   cbcecccbcddd     512     -512
72   bafaecacabdd    -288      288
74   bbcccddcdcdd   -4448     4448
75   aeaecbccdddd    -704     -448
76   baacacccaeee     352     -352
79   aecaabacdcce    -688      688
82   bbddbbccbddd     368      256
88   cbaacaccdddd    1920        0
89   aecbbbaccbdd     512     -512
93   babbdccbcdce     624     -624
95   baafabceecee    1120    -1120
97   bafffabacaee     128     -128
99   cbacceaaeeae    1312    -1312
100  bcacaceacecd    -128      128
101  babaccacbaee     -56       56
105  bbaabbbcbbdd     768     -768
106  acabaecaeeae     256     -256
107  afbbbfacddce    6208    -6208
108  bbbfabcbabdd   -1960     1960
110  abbcdbbacbdd    -416      416
111  bbbcddcacbdd    -848      848
113  cdddcdccecce  -15360   -15056
116  aceccbfbdbdd    -320      320
118  bccbbcdbacdd    -832      832
119  cdcaaffacddd    1024    -1024
121  abceafbffbdd    -704      704
122  ccacbcacafbd      -8        8
123  bdbdcecbceae     384     -384
124  cccafbfabbdd     128     -128
125  baabbdbcbfbd    -560      560
126  afbfabacabdd    -520      520
127  baceaabacbdd     256     -256
131  bdddcdddccce   45824    45888
135  bddbdcecdddd  -16256   -17408
136  bccacbcacbdd    -712      712
137  aababccabfbd     416     -416
139  cceabbacabdd     120     -120
144  caaabababdbd     832     -832
146  bbfbfbcaeeae      32      -32
149  aabbddbbcbdd     544     -544
150  baaacbcccece     120     -120
153  bfafabbfafae     144     -144
155  bddceaeabaee   -1408     1408
157  affafbcacbdd   -1472     1472
158  aecbaafaaeae     192     -192
162  bdbdcccaffae      32      -32
167  baceccbbdbdd      32      -32
170  aaccabbabcdd     312     -312
173  accaeacecbdd    -704      704
175  aaecbffbfbdd   -2816     2816
178  cbcbdcacdcce   -1024     1024
180  ceeaacbaffbd     512     -512
184  ababfbcceccd     416      160
185  bdcccccafaee     208      464
186  cdbfafaeaece     512      256
187  afabafafabdd    -832      832
188  ceeeeaeeaaae   45056    45888
189  bfafabaabdce    -632      632
190  aecaceaabdce    -256      256
193  bcdcaceeeccd     448      960
195  bafbacbbccdd     136     -136
196  aabcabbddcee    -464      -16
197  baffabbaffbd    -208      -80
198  cddbfabfffae   -3392    -3264
202  aeacdcbbdccd     768     -768
203  bcbddcbaffae     400     -400
205  aaeeecaaffae    -544        0
206  bffbdbfaecdd   -1792    -1536
207  cceeaeaccecd     864     -864
212  cecbfabbaecd    -384      384
213  babafabfffae    1248      896
215  bcaabccaabdd     -64       64
216  cbbcaecaffae     -32       32
218  ccdbcddbcdce     784     -784
223  bdbbbcceabdd      48      -48
224  abaabbbcbbdd   -1280     1280
225  abcdbcceccce     512     2048
227  abbbbbfaabdd     240     -240
228  ccaeeaceccce   -2400     -864
231  accaaecbbdce     -80       80
232  bccafbbcaaee     416     -416
234  aaafafaeafae   24096   -24096
235  cddbbddddbbd   31488    23808
237  baaacbcbfbdd    -480      480
238  bcbbcbaceeae     608      960
239  ccdcabbacbdd     120     -120
240  cccbababafaf     904     1016
241  cddbacecbdbd     704     -704
242  cbbbbaaffbdd   -1456     1456
244  bffaccdbcdce     704     -704
248  cccddcbcdbdd       0    -3040
250  cacabbbaecce    -112      112
252  acbbaaaabcee    -688      688
253  ccaecbfaeeae    -576      576
254  babbcbcaecee    1392    -1392
256  bddbcabcdcee   -1040    -1008
257  abaeabaabdbd     256     -256
258  aabbcccccece     256     -256
259  bacaafaafbbf     512        0
263  cbaaeccbceee    -512     -256
264  cacaeaacdcce   -1216     1216
266  bcddcceaaaaf    -768      768
267  acceeccabddd    -496      496
268  ceaaceabccee    -128      128
271  cccaeaaeaecd   -1728    -1152
272  cdbafaaaaece    -768      768
275  bdcafaaacddd    1536     2560

In [71]:
right_df = pd.merge(bad_mix_df, bad_6trim_df, how ='right', on =['word'], indicator=True)
right_df = right_df[right_df["_merge"]=="right_only"].drop(columns=['tgt_x','pred_x','_merge'])
right_df = right_df.rename(columns={'tgt_y': 'tgt', 'pred_y': 'pred_6'})
pd.set_option('display.max_rows', 500)
print(right_df)

              word    tgt pred_6
0     caabddbdbdce   -768    768
1     aeafabfaeaee    256   -256
2     ccaceeccdbdd    480   -480
4     ccddbbccbddd     48    -48
5     ccaeccdbbbdd    128   -448
...            ...    ...    ...
1367  bbccbfbceece   -896    896
1368  aaaaecdbbbdd  10272  -3072
1369  aaabfbbcddcd    736   -736
1370  aeecceabaece    768   -768
1371  aaecbbaceeae   -128    128

[1241 rows x 3 columns]

In [72]:
len(joint_df)+len(left_df)==len(bad_mix_df)

True

In [73]:
len(joint_df)+len(right_df)==len(bad_6trim_df)

True

In [74]:
left_df

             word     tgt pred_mix
0    babcbcdcabdd     416     -416
1    abbffbabfbdd     224     -224
6    abbbcccbdddd     576     -576
8    abbfbbbfacdd   -3696     3696
9    acaccaabaeae     -24       24
10   bcdceeaeaeae   -1664    -3072
11   afbacbbfabdd     -80       80
16   aafafacacbdd     112     -112
17   ccbdcbdbcece    -320      320
21   bacaecdcdcce   -1664    -1472
22   bfaaeaccdddd    -640      640
23   aaaaaacdbbdd       0     1056
25   cddbcaafaaaf   -5760     5760
26   cdbbffbbffae    -992    -1376
28   baffaeabccee     160     -160
29   afbacaeabddd    -608      608
30   bbcbacdbacdd     176     -176
32   babcacdceece    -672      672
34   bcaafaabbdce     128     -128
36   caaccbfbddce     192       96
40   aeaacccacece     824     -824
42   cacbbfbcbbdd    -208      208
43   ceaaaccbcddd      80      -80
44   cecdbbbcabff     512     -512
46   bdcbbbbbbbdd     480     -480
47   cbcdcaabacdd    -208      208
48   aaffabdcaeae    -160      160
49   afafbcabfbdd    -800      800
50   cbabfabbcbdd     256     -256
57   bdbbbdcccdce   -3968     3968
58   babafabbabdd    -384      384
59   caecabffbbdd    -960      864
61   afbaabfacdcd     -48       48
63   bcbccaaafbdd    -544      544
64   aabdbbbbfbdd   -1120     1120
65   cabcacdddcce    1312     1952
67   cdcbcccabcee    -128      128
69   afaacaabdddd    -176     -768
71   cbcecccbcddd     512     -512
72   bafaecacabdd    -288      288
74   bbcccddcdcdd   -4448     4448
75   aeaecbccdddd    -704     -448
76   baacacccaeee     352     -352
79   aecaabacdcce    -688      688
82   bbddbbccbddd     368      256
88   cbaacaccdddd    1920        0
89   aecbbbaccbdd     512     -512
93   babbdccbcdce     624     -624
95   baafabceecee    1120    -1120
97   bafffabacaee     128     -128
99   cbacceaaeeae    1312    -1312
100  bcacaceacecd    -128      128
101  babaccacbaee     -56       56
105  bbaabbbcbbdd     768     -768
106  acabaecaeeae     256     -256
107  afbbbfacddce    6208    -6208
108  bbbfabcbabdd   -1960     1960
110  abbcdbbacbdd    -416      416
111  bbbcddcacbdd    -848      848
113  cdddcdccecce  -15360   -15056
116  aceccbfbdbdd    -320      320
118  bccbbcdbacdd    -832      832
119  cdcaaffacddd    1024    -1024
121  abceafbffbdd    -704      704
122  ccacbcacafbd      -8        8
123  bdbdcecbceae     384     -384
124  cccafbfabbdd     128     -128
125  baabbdbcbfbd    -560      560
126  afbfabacabdd    -520      520
127  baceaabacbdd     256     -256
131  bdddcdddccce   45824    45888
135  bddbdcecdddd  -16256   -17408
136  bccacbcacbdd    -712      712
137  aababccabfbd     416     -416
139  cceabbacabdd     120     -120
144  caaabababdbd     832     -832
146  bbfbfbcaeeae      32      -32
149  aabbddbbcbdd     544     -544
150  baaacbcccece     120     -120
153  bfafabbfafae     144     -144
155  bddceaeabaee   -1408     1408
157  affafbcacbdd   -1472     1472
158  aecbaafaaeae     192     -192
162  bdbdcccaffae      32      -32
167  baceccbbdbdd      32      -32
170  aaccabbabcdd     312     -312
173  accaeacecbdd    -704      704
175  aaecbffbfbdd   -2816     2816
178  cbcbdcacdcce   -1024     1024
180  ceeaacbaffbd     512     -512
184  ababfbcceccd     416      160
185  bdcccccafaee     208      464
186  cdbfafaeaece     512      256
187  afabafafabdd    -832      832
188  ceeeeaeeaaae   45056    45888
189  bfafabaabdce    -632      632
190  aecaceaabdce    -256      256
193  bcdcaceeeccd     448      960
195  bafbacbbccdd     136     -136
196  aabcabbddcee    -464      -16
197  baffabbaffbd    -208      -80
198  cddbfabfffae   -3392    -3264
202  aeacdcbbdccd     768     -768
203  bcbddcbaffae     400     -400
205  aaeeecaaffae    -544        0
206  bffbdbfaecdd   -1792    -1536
207  cceeaeaccecd     864     -864
212  cecbfabbaecd    -384      384
213  babafabfffae    1248      896
215  bcaabccaabdd     -64       64
216  cbbcaecaffae     -32       32
218  ccdbcddbcdce     784     -784
223  bdbbbcceabdd      48      -48
224  abaabbbcbbdd   -1280     1280
225  abcdbcceccce     512     2048
227  abbbbbfaabdd     240     -240
228  ccaeeaceccce   -2400     -864
231  accaaecbbdce     -80       80
232  bccafbbcaaee     416     -416
234  aaafafaeafae   24096   -24096
235  cddbbddddbbd   31488    23808
237  baaacbcbfbdd    -480      480
238  bcbbcbaceeae     608      960
239  ccdcabbacbdd     120     -120
240  cccbababafaf     904     1016
241  cddbacecbdbd     704     -704
242  cbbbbaaffbdd   -1456     1456
244  bffaccdbcdce     704     -704
248  cccddcbcdbdd       0    -3040
250  cacabbbaecce    -112      112
252  acbbaaaabcee    -688      688
253  ccaecbfaeeae    -576      576
254  babbcbcaecee    1392    -1392
256  bddbcabcdcee   -1040    -1008
257  abaeabaabdbd     256     -256
258  aabbcccccece     256     -256
259  bacaafaafbbf     512        0
263  cbaaeccbceee    -512     -256
264  cacaeaacdcce   -1216     1216
266  bcddcceaaaaf    -768      768
267  acceeccabddd    -496      496
268  ceaaceabccee    -128      128
271  cccaeaaeaecd   -1728    -1152
272  cdbafaaaaece    -768      768
275  bdcafaaacddd    1536     2560

In [75]:
joint_df

             word     tgt pred_mix  pred_6
0    bbbaaafaeaee     768    -1568    1760
1    aaaecbfbabdd   -1904     1904    1904
2    bfbfabacecdd    -944      944    1248
3    ccbdbbcbceee    1296     1136    1104
4    bbbabffbcece     288     -288    -288
5    bbbabdccdccd     928      512     416
6    aacdbaabaece    -128      128     128
7    aacdcbaacecd    -128      128     128
8    cbceecacbcee     384     -384    -384
9    ccababfbfbdd    1760      192   -1824
10   bbbaeaacafbd    -576      576     576
11   bbcaffbbfbbd   -2752    -1216    1216
12   ccaffacdcecd    -512      512     512
13   ccabcafbbbdd   -1072    -1440     496
14   aeaaafbfbcdd   -1216     1216    1216
15   aeacbabfaeee    1280    -1248    1248
16   aaeeabcccddd     720     -720    -624
17   baaafabcdbdd     992     -992    -992
18   bbafbbcaccdd    -256      256     256
19   bbbacabcbbdd    -120      120     120
20   bbaacbdbaeee    1120    -1120   -1120
21   aacddbbbacdd     160     -160    -160
22   aabccdcceeae     160       32    -608
23   bbdbaaaeafae    -336      336    -112
24   acaeaccacece    -144      144     144
25   cbbbfffbdddd    5248    -5248  -11520
26   aacaeabaeeee    -256      256     256
27   bcbccabaeece    1040    -1040   -1232
28   caeacaabdddd   -3040     3040    1280
29   bbdceceaabdd      64      -64     -64
30   aafabfbcbcdd     176     -176    -176
31   ccbafbabccdd     416     -416    -416
32   bccccdcacbdd    -864      864     864
33   bbceabcabfbd    -256      256     256
34   ccbacecdcccd    3072    -3072     -64
35   aacbffaaafae   -2144     2144     608
36   ccabbfbbbbdd     672     -672    -672
37   bbfacaabccdd     120     -120    -120
38   bbbaceaeccee    -416       32     864
39   aaafaaaacdce   10776   -10776  -10776
40   bcbbaecdbdce   -1152    -1024    1152
41   ccecceecdbdd    2240     1088    1600
42   aaacbceabbdd     576     -576    -576
43   bdcabbcdceae    -384      384     384
44   bbaceceaeaaf    -640      640     640
45   cceceaeeecce    -256     -640   -1408
46   bccacbbbffbd    -672     -752    -624
47   ccbccccacbdd   -1200     1200    1200
48   ccbacaabdddd   -3024     3024    3024
49   ccdbbaaaccdd     192     -192    -192
50   accaecabdddd    3008    -3008   -3008
51   afaafbabbaee    1496    -1496   -1496
52   bbabbccdbddd    2032    -1792   -1768
53   acaabaacdddd   10560   -10560   -6192
54   ceecdcaaacdd    1344    -1344   -1344
55   aafaeceeecce   -4608    -4864   -3456
56   ccaaaecbffae   -1088     -800    1088
57   cceeecccdddd  -48192    48192   47712
58   cbbcbbcabfbd    -904      904     904
59   aabcaceaffae     640     -640   -1216
60   bbaabcddcece   10592   -10592  -10592
61   ceabbdbbceee   -1536     1536    1536
62   ccecdcbbbbdd     576     -576    -576
63   caaeacbddddd    3392    -3392   -6912
64   bcdbdbafaeae     464     -464    -464
65   aacabcaffaee   -1600     1600    1600
66   accaffaecddd   -2112    -2560      64
67   bdddccacbbff    1152    -1152   -1152
68   aaaaecaacecd   30480   -30480  -30480
69   ccdccbacdddd    -704      704     704
70   ccbfbbbdcdce    1600    12272   -1600
71   ceecdcabcece    -128      128     128
72   aaceaeaececd     384      448     640
73   aacecdbffbdd    2944     2880   16064
74   cceabcceafbd    -240      240     240
75   ccbceaccddce     736     -736    -736
76   bbbafaaaeeee    2016    -2016    5856
77   ccbbabbdbfae    -640      640     640
78   cbcbaabdbfae      80      -80     -80
79   aaccbcecabdd     560     -560    -560
80   babbbddddddd   86400   -86400  -45824
81   ababceacabdd     560     -560    -560
82   bbdccaeaaaee    -912      912   -1200
83   ccabbbceafae    1152    -1152   -1152
84   bbbfaacacddd   -1456    -2256   -3520
85   acbaaacdbcee     384     -384    -384
86   ccbffaeabcee     192     -192    -192
87   aaaabbfacaee     192     -192    -192
88   ccccbddcbbdd     896      320    -800
89   aacbfbcaeeae     992     -992    -992
90   bcbfbccbdddd     416     -416    -416
91   baabfbacbcee    -608      608     608
92   bbbdbacaeeee    5728    -5728   -3680
93   aaeeabbfbbdd      96      -96    -224
94   ccaeabdccddd    1120      992     992
95   bbbdbbcbcdcd   11064   -11064  -11544
96   bbfbbcbdcaee    -432      432     432
97   aaacbcaffbdd   -2000     2000    2000
98   aafbceaaeecd      32      -32     352
99   ceecbabbcdcd   -2800     2800    2800
100  aabdbbaeaaee     576     -576    -576
101  abbfbdcecddd     832       64    -832
102  cecaeaabbddd     512      256    -512
103  bdddcccaeeae   -2592    -4384     992
104  bbabccabcdbd    -392      392     392
105  acaccdcdbbdd   -1120     1120    1024
106  bbdccbbceeae    6368    -6368   -6368
107  aabfbfafbdce    -288      288     -96
108  cccbababbbdd    -904      904     904
109  bcaceaeaaeae   -1344    -1216    1344
110  bacaaaececce    1920     1280    1664
111  bccacabdddcd     720     -720    -592
112  aaaffabbabdd     616     -616    -616
113  bbdccacbaaee    -280      280     280
114  ccdbcbabfbff    -784     -592     784
115  ccbceeaaaeae     608     1952    -608
116  cdcdcceafaee   -1472     1376    1472
117  bbbbbfaaeaee  -29984    29984   30688
118  bbbbbffbafbd     384     -384    -384
119  bbdceacbdbdd    -576      576     576
120  abafbcaffbdd    -672      672     672
121  bbceaeccdddd   -1088    -1280   -1472
122  cdbaeaabacdd    -384      384     384
123  bbcaffbbbfae    -160      160     160
124  bbfbaabffbdd    1024     2304   -1024
125  ccbccacecece     528      176     272
126  caafaaacabdd    -256      256     256
127  aabcbcaaacdd    -200      200     200
128  babddbacabdd    -608      608     608
129  bbcdbbabacdd     208     -208    -208
130  aabdbaeeeaff    1152    -1152   -1152

In [76]:
right_df

              word    tgt pred_6
0     caabddbdbdce   -768    768
1     aeafabfaeaee    256   -256
2     ccaceeccdbdd    480   -480
4     ccddbbccbddd     48    -48
5     ccaeccdbbbdd    128   -448
...            ...    ...    ...
1367  bbccbfbceece   -896    896
1368  aaaaecdbbbdd  10272  -3072
1369  aaabfbbcddcd    736   -736
1370  aeecceabaece    768   -768
1371  aaecbbaceeae   -128    128

[1241 rows x 3 columns]